export interface DropTransactionModel  {
  id: number,
  indicator: string,
  transactionId: string,
  deviceNumber: string,
  bagNumber: string,
  containerType: string,
  transmitionDate: null,
  merchantNumber: number,
  totalCoins: number,
  totalNotes: number,
  totalAmount: number,
  currency: string,
  canisterNumber: number,
  denomination: {
    denomination1: number,
    denomination2: number,
    denomination3: number,
    denomination4: number,
    denomination5: number,
    denomination6: number,
    denomination7: number,
    denomination8: number,
    denomination9: number,
    denomination10: number,
    denomination11: number,
    denomination12: number,
    denomination13: number,
    denomination14: number,
    denomination15: number
  },
  depositReference: string,
  sequenceNumber: number,
  settlementFlag: string
}
